extraEnv:
- name: AWS_DEFAULT_REGION
  value: "${region}"
- name: AWS_REGION
  value: "${region}"
- name: AWS_ROLE_ARN
  value: "arn:aws:iam::${account_id}:role/external-secrets.kube-system.sa.${name}"
- name: AWS_WEB_IDENTITY_TOKEN_FILE
  value: "/var/run/secrets/amazonaws.com/serviceaccount/token"
- name: AWS_STS_REGIONAL_ENDPOINTS
  value: "regional"
extraVolumes:
- name: aws-token
  projected:
    sources:
    - serviceAccountToken:
        audience: "amazonaws.com"
        expirationSeconds: 86400
        path: token
extraVolumeMounts:
- mountPath: "/var/run/secrets/amazonaws.com/serviceaccount/"
  name: aws-token
