apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
- name: external-secrets
  namespace: kube-system
  repo: https://charts.external-secrets.io
  version: 0.19.2
  releaseName: external-secrets
  includeCRDs: true
  valuesFile: values.yaml
