resources:
  requests:
    cpu: 10m
    memory: 32Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

certController:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
