---
name: Updatecli

on:
  # Trigger Updatecli if a new commit land on the main branch
  push:
    branches: [ main ]
  # Manually trigger Updatecli via GitHub UI
  workflow_dispatch:
  # Trigger Updatecli once day by a cronjob
  schedule:
  # * is a special character in YAML, so you have to quote this string
  # Run once a day
  - cron: '0 0 * * *'

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  updatecli:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Install Updatecli in the runner
      uses: updatecli/updatecli-action@5bda7da77bf4d181bce5f807d73d832b62062acf # v3.3.0

    - uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5
      id: kubectl

    - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
      id: helm
      with:
        version: '4.2.2'

    - name: Get token
      id: get_token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
      with:
        app-id: ${{ secrets.UPDATECLI_APP_ID }}
        private-key: ${{ secrets.UPDATECLI_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Run Updatecli in apply mode
      run: "updatecli --experimental apply --config ./updatecli/updatecli.d --values updatecli/values.yaml --clean=true"
      env:
        UPDATECLI_GITHUB_TOKEN: '${{ steps.get_token.outputs.token }}'
